### ISSUE TITLE
[Project Metadata Update] Add/Update Project: Lulo

### ISSUE THREAD

**Issue by nicechute** [switchboard-xyz/ecosystem#2]
### Project Information

**Project Name:**  
Lulo

**Project Brief:**  
Your DeFi Savings Account

**Image:**  
<Attach the project image to this issue.>
![lulo logo](https://github.com/switchboard-xyz/ecosystem/assets/83227620/6e21a972-96e2-4be1-853a-ab8799a27152)

**Website:**  
(https://lulo.fi/)

**X (formerly Twitter):**  
[@uselulo
(https://twitter.com/uselulo)

**GitHub:**  
(https://github.com/lulo-labs)

**Telegram:**  
@uselul

**Discord:**  
(https://discord.gg/lulo)

### Additional Information

<Provide any additional information / questions.>

### Change Request

**Is this a new entry or an update to an existing entry?**

- [x] New entry
- [ ] Update to an existing entry

**If updating, what is the current name of the project in the repository?**  
<Provide a link to the project's existing metadata file (if applicable).>

### Checklist

- [x] I have checked that the information provided is accurate and up-to-date.
- [x] I understand that the information provided will be publicly accessible.

---

Thank you for contributing to the Switchboard ecosystem!

**Comment by jessupjn** [comment]
Submitted: https://github.com/switchboard-xyz/ecosystem/commit/1d982bd16f92ff37011ca5724485191b3054e29a
